### ISSUE TITLE
Migrate hasjob to AWS

### ISSUE THREAD

**Issue by karthikb351** [hasgeek/hasjob#311]
| Current implementation   |      On AWS      |
|----------|-------------|
| Hasjob server under uwsgi |  Docker container running hasjob under uwsgi |
| Postgres database running locally |    AWS RDS Postgres   |
| Redis service running locally | Redis container for hasjob containers to talk to |
| Postfix service running locally | Postfix running within hasjob’s container |
| Lastuser service via HTTP (but essentially local) | Lastuser via HTTP (not local) or should Lastuser be migrated to AWS too? |

### Tasks
- [x] Setup environment for hasjob within docker
- [x] Hasjob talks to external redis container
- [x] Hasjob has docker specfic config file that reads from env vars
- [ ] Start up script for docker which auto runs migrations on booting up the container (#305)
- [x] Postfix config that reads from env vars (#306)
- [ ] Populate Amazon RDS with dummy data (#307)
- [ ] Setup Travis to build docker images and push to Docker Hub (#310)
